version: "3.1"
services:
  pylucene:
    container_name: pylucene
    build: ./pylucene/
    image: pylucene
    ports:
      - "8043:8043"
    networks:
      - maestro_traefik
    volumes:
      - ./data:/index/
      - ./pylucene/:/python-docker
    environment:
      - SE_ALLOW_UNSAFE_SSL=TRUE
      - DEBUG=TRUE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pylucene.rule=Host(`maestro.localhost`)"
      - "traefik.http.routers.pylucene.rule=PathPrefix(`/pylucene`)"
      - "traefik.http.routers.pylucene.entrypoints=websecure"
      - "traefik.http.routers.pylucene.tls=true"
      - "traefik.http.routers.pylucene.middlewares=pylucene"
      - "traefik.http.middlewares.pylucene.stripprefix.prefixes=/pylucene"

  availability-proxy:
    container_name: availability-proxy
    build: ./status_proxy
    image: availability-proxy
    networks:
      - maestro_traefik
    ports:
      - "8042:8042"
    volumes:
      # - ./data:/index/
      - ./status_proxy/app:/app
    environment:
      - SE_BACKEND_SERVER=https://172.30.0.1:4269/pylucene
      - SE_ALLOW_UNSAFE_SSL=TRUE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.availability-proxy.rule=Host(`maestro.localhost`)"
      - "traefik.http.routers.availability-proxy.rule=PathPrefix(`/search-engine`)"
      - "traefik.http.routers.availability-proxy.entrypoints=websecure"
      - "traefik.http.routers.availability-proxy.tls=true"
      - "traefik.http.routers.availability-proxy.middlewares=availability-proxy"
      - "traefik.http.middlewares.availability-proxy.stripprefix.prefixes=/search-engine"

networks:
  maestro_traefik:
    external: true
